# Generated by Django 3.1.7 on 2021-04-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='karma',
            field=models.IntegerField(default=0),
        ),
    ]
